services:
  nginx-mailer:
    image: drumsergio/nginx-mailer:latest
    container_name: nginx-mailer
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/website:/usr/share/nginx/html:ro
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT:-465}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      CONTACT_EMAIL: ${CONTACT_EMAIL}
    networks:
      - tipi_main_network
    labels:
      traefik.enable: true
      traefik.http.middlewares.nginx-mailer-web-redirect.redirectscheme.scheme: https
      traefik.http.services.nginx-mailer.loadbalancer.server.port: 80
      traefik.http.routers.nginx-mailer-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.nginx-mailer-insecure.entrypoints: web
      traefik.http.routers.nginx-mailer-insecure.service: nginx-mailer
      traefik.http.routers.nginx-mailer-insecure.middlewares: nginx-mailer-web-redirect
      traefik.http.routers.nginx-mailer.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.nginx-mailer.entrypoints: websecure
      traefik.http.routers.nginx-mailer.service: nginx-mailer
      traefik.http.routers.nginx-mailer.tls.certresolver: myresolver
      traefik.http.routers.nginx-mailer-local-insecure.rule: Host(`nginx-mailer.${LOCAL_DOMAIN}`)
      traefik.http.routers.nginx-mailer-local-insecure.entrypoints: web
      traefik.http.routers.nginx-mailer-local-insecure.service: nginx-mailer
      traefik.http.routers.nginx-mailer-local-insecure.middlewares: nginx-mailer-web-redirect
      traefik.http.routers.nginx-mailer-local.rule: Host(`nginx-mailer.${LOCAL_DOMAIN}`)
      traefik.http.routers.nginx-mailer-local.entrypoints: websecure
      traefik.http.routers.nginx-mailer-local.service: nginx-mailer
      traefik.http.routers.nginx-mailer-local.tls: true
      runtipi.managed: true
