services:
  nginx-mailer:
    image: drumsergio/nginx-mailer:1.0.0
    container_name: nginx-mailer
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/website:/usr/share/nginx/html:ro
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT:-465}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      CONTACT_EMAIL: ${CONTACT_EMAIL}
    x-runtipi:
      is_main: true
      internal_port: 80

x-runtipi:
  schema_version: 2
