services:
  way-cms-website:
    image: nginx:1.29-alpine
    container_name: way-cms-website
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/website:/usr/share/nginx/html:ro

  way-cms-admin:
    image: drumsergio/way-cms:2.0.22
    container_name: way-cms-admin
    restart: unless-stopped
    depends_on:
      - way-cms-website
    volumes:
      - ${APP_DATA_DIR}/data/website:/var/www/html:rw
      - ${APP_DATA_DIR}/data/backups:/.way-cms-backups:rw
      - ${APP_DATA_DIR}/data/cms-data:/.way-cms-data:rw
    environment:
      CMS_BASE_DIR: /var/www/html
      CMS_USERNAME: ${CMS_USERNAME:-admin}
      CMS_PASSWORD: ${CMS_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      MULTI_TENANT: "false"
      AUTO_BACKUP_ENABLED: "true"
      PORT: "5000"
      FLASK_APP: app.py
    x-runtipi:
      is_main: true
      internal_port: 5000

x-runtipi:
  schema_version: 2
