services:
  pumperly:
    image: drumsergio/pumperly:v1.2.7
    container_name: pumperly
    restart: unless-stopped
    depends_on:
      pumperly-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://pumperly:${PUMPERLY_DB_PASSWORD}@pumperly-db:5432/pumperly
      VALHALLA_URL: http://pumperly-valhalla:8002
      PHOTON_URL: http://pumperly-photon:2322
      NEXT_PUBLIC_APP_URL: ${APP_PROTOCOL:-http}://${APP_DOMAIN}
      NEXT_PUBLIC_DEFAULT_LOCALE: en
      NEXT_PUBLIC_DEFAULT_FUEL_TYPE: E5
    x-runtipi:
      is_main: true
      internal_port: 3000

  pumperly-db:
    image: postgis/postgis:17-3.5-alpine
    container_name: pumperly-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pumperly
      POSTGRES_USER: pumperly
      POSTGRES_PASSWORD: ${PUMPERLY_DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pumperly"]
      interval: 10s
      timeout: 5s
      retries: 5

  pumperly-valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:3.5.1
    container_name: pumperly-valhalla
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/valhalla:/custom_files

  pumperly-photon:
    image: komoot/photon:1.0.1
    container_name: pumperly-photon
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/photon:/photon/photon_data

x-runtipi:
  schema_version: 2
