services:
  epublangmerger:
    image: drumsergio/epublangmerger:1.0.1
    container_name: epublangmerger
    restart: unless-stopped
    x-runtipi:
      is_main: true
      internal_port: 3838

x-runtipi:
  schema_version: 2
