services:
  audio-transcode-watcher:
    image: drumsergio/audio-transcoder:0.4.2
    container_name: audio-transcode-watcher
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
      - ${APP_DATA_DIR}/data/music:/music

x-runtipi:
  schema_version: 2
